name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: Upload built apk
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: snapshot
        path: |
              ${{ github.workspace }}/app/build/outputs/apk
              ${{ github.workspace }}/app/build/outputs/mapping
